run:
  timeout: 2m

linters:
  enable:
    - exportloopref
    - goconst
    - godot
    - goimports
    - unconvert
    - whitespace

linters-settings:
  errcheck:
    ignore: net/http:Write
  goconst:
    min-len: 2
    min-occurrences: 2
