name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ~1.16
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39
